### PR TITLE
Allow multiple --vars-data arguments

### LINKED ISSUE #45: Allow multiple --vars-data arguments
Currently it's not possible to pass multiple instances of --vars-data to teflo. It would be very useful to allow this.

Additionally, the documentation makes no comment about the structure of the data, as best I can tell, that needs to be inside of the vars-data file. It should be mentioned that a YAML-formatted file is expected.

### PR DESCRIPTION
**Pull request by greg-hellings**
Implements allowing --vars-data to be passed to teflo multiple times.

Fixes #45 
Depends on #48 merging first

### CODE REVIEW

**Review by rujutashinde — COMMENTED** [review]
LGTM. It looks like the other PR #48  changes are already present in this ?

**Comment by greg-hellings** [comment]
Correct. I had to make those changes in order to get the tests in correctly for this. This branch came right off the tip of that one.

**Comment by rujutashinde** [comment]
@greg-hellings Sorry i just saw you sent the PR against the master branch. Could you send it against the develop. this way the checks along with your new tests will run
We do PR against the develop branch, and only push develop to master during the release. https://teflo.readthedocs.io/en/latest/developers/development.html#submitting-the-pr

**Comment by greg-hellings** [comment]
This should be updated. Can we get it merged?

**Review by rujutashinde — APPROVED** [review]

**Pull request merged**
