### PR TITLE
Fix issues of jinja templating in include

### PR DESCRIPTION
**Pull request by JunqiZhang0**
1. Added toggle_jinja_include parameter under defaults section in
       teflo.cfg to enable the ability for teflo to handle the jinja templating in include section
    2. Added unit tests
    3. Added Documentation and example

### CODE REVIEW

**Review by rujutashinde — COMMENTED** [review]
Overall LGTM, I have not pulled the code and tested it though, but the unit test looks good.
This will close issue #132  correct?

**Comment by JunqiZhang0** [comment]
@rujutashinde Yes

**Review by rujutashinde — APPROVED** [review]

**Comment by JunqiZhang0** [comment]
hi @jbpratt ,  I made this under a setting because we are not sure if this will cause regression. The default behavior didn't change. So if you don't set this variable, it will work exactly like before.

**Comment by ryankwilliams** [comment]
@JunqiZhang0 I give a +1 to what @jbpratt has mentioned. Why can't this just be default behavior? By default teflo supports jinja, so I personally I feel it should be supported by default for both standard SDF or included SDF. Over now needing to toggle on another flag in the config file. I would assume teflo would have tests to cover this functionality to ensure no new regressions would be introduced with this change?

**Comment by dno-github** [comment]
Hi @ryankwilliams` @jbpratt , so I had a discussion with teflo team, and we decided to have this well tested(with this feature as a default behavior), if it goes well and pass all the tests, we can make this as a default behavior.

**Pull request merged**
