### PR TITLE
CCITCARBON-386 test the jinja template issue

### PR DESCRIPTION
**Pull request by shay6**

### CODE REVIEW

**Comment by shay6** [comment]
Hey @jbpratt and @ryankwilliams, can you please share your use case (of jinja templates) just to be sure that our code works as expected for you?

Thanks!

**Comment by shay6** [comment]
@jbpratt I think I have found [here](https://gitlab.cee.redhat.com/mpqe/mps/solutions/cnv_odf_ocp/-/tree/develop/cnv_odf_ocp/teflo) some examples

**Comment by jbpratt** [comment]
Hey @shay6 thanks for digging, yeah that is the project where we ran into this issue IIRC

**Comment by rujutashinde** [comment]
LGTM, we can merge this. Please make sure we have similar use case covered in our e2e test suite. Once that is done you can mark that JIRA ticket as closed

**Pull request merged**
